# Generated by Django 6.1.1 on 2026-09-04 10:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refugee_support', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refugee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)])),
                ('last_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)])),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('nationality', models.CharField(choices=[('Ugandan', 'Ugandan'), ('Kenyan', 'Kenyan'), ('Tanzanian', 'Tanzanian'), ('Burundian', 'Burundian'), ('Rwandanese', 'Rwandanese'), ('Somali', 'Somali'), ('South Sudanese', 'South Sudanese')], max_length=50)),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed'), ('Windowed', 'Windowed')], max_length=20)),
                ('settlement_camp', models.CharField(choices=[('Gulu settlement camp', 'Gulu settlement camp'), ('Arua settlement camp', 'Arua settlement camp'), ('Mbarara settlement camp', 'Mbarara settlement camp'), ('Kasese settlement camp', 'Kasese settlement camp'), ('Busia settlement camp', 'Busia settlement camp'), ('Mbale settlement camp', 'Mbale settlement camp'), ('Kigezi settlement camp', 'Kigezi settlement camp')], max_length=100)),
                ('date_of_joining_settlement_camp', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='RefugeeSupport',
        ),
    ]
